### ISSUE TITLE
StrictMode Causing Problems with console.log()

### ISSUE THREAD

**Issue by jamrsim** [nishant-666/React-CRUD-Operation-V2#1]
index.js with

```
ReactDOM.render(
  <React.StrictMode>
  <App />
  </React.StrictMode>, 
  
  document.getElementById('root')
  )
```

console.log() from create.js does not work.  Removing React.StrictMode allows console.log to work.

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at input
    at RefFindNode (http://localhost:3000/static/js/vendors~main.chunk.js:365:35)
    at Ref (http://localhost:3000/static/js/vendors~main.chunk.js:298:24)
    at div
    at Checkbox (http://localhost:3000/static/js/vendors~main.chunk.js:69521:29)
    at div
    at FormField (http://localhost:3000/static/js/vendors~main.chunk.js:58966:24)
    at form
    at Form (http://localhost:3000/static/js/vendors~main.chunk.js:58653:29)
    at div
    at Create (http://localhost:3000/static/js/main.chunk.js:301:91)
    at div
    at div
    at App`

**Comment by jamrsim** [comment]
Thank you for the great tutorial.  Appreciate the PR for future tutorial followers.
